### ISSUE TITLE
broken link

### ISSUE THREAD

**Issue by seguri** [CGamesPlay/infra#3]
Hi! `generate_installer.sh` linked in [chapter 3](https://cgamesplay.com/post/2021/10/27/creating-my-personal-cloud-with-hashicorp/) is no longer available :)

**Comment by CGamesPlay** [comment]
Hello! Sorry about that. I migrated the infrastructure to Ansible about 9 months ago. The latest version of generate_installer.sh is [here](https://github.com/CGamesPlay/infra/blob/8649f4d8856dedfab201f3c6f5135c99467d24bd/bootstrap/generate_installer.sh).

I'll write an update about this in the blog at some point, so thanks for pointing this out (in the mean time I'll fix the link). The reason I switched to Ansible is that the generate_installer.sh path, while easier to initially deploy, ended up being harder to maintain and make updates. Ansible is more complicated to develop on (because it's not a simple bash script), but it handles making sure the server stays up to date better. This is important because this repo doesn't use immutable servers.
